[package]
name = "jh"
version = "0.2.0"
authors = ["Olivier Lauzon <olauzon@gmail.com>"]

[dependencies]
jumphash = { git = "https://github.com/olauzon/jumphash", rev = "ae332fd2" } 
actix-web = "1.0"
serde = "1.0"
serde_derive = "1.0"
clap = "2.33"
